export const SamuelDMarcusTxData = [
  {
    txName: "Cash for Gold",
    whatUsed: "Credit",
    credit: "+£500,000.00",
    date: "Aug 5, 2023",
    color: "green",
  },
  {
    txName: "Interest",
    whatUsed: "Credit",
    credit: "+£17,000.00",
    date: "Apr 15, 2023",
    color: "green",
  },
  {
    txName: "Cash for Gold",
    whatUsed: "Credit",
    credit: "+£500,000.00",
    date: "Mar 25, 2023",
    color: "green",
  },
  {
    txName: "Zelle Payment from Terry Lance",
    whatUsed: "Credit",
    credit: "+£2000.00",
    date: "Mar 15, 2023",
    color: "green",
  },
  {
    txName: "Cash for Gold",
    whatUsed: "Credit",
    credit: "+£518,705.25",
    date: "Mar 9, 2023",
    color: "green",
  },
  {
    txName: "Payroll",
    whatUsed: "Credit",
    credit: "+£19,928.72",
    date: "Feb 22, 2023",
    color: "green",
  },
  {
    txName: "VAT Reversed",
    whatUsed: "Credit",
    credit: "+£9,928.72",
    date: "Feb 10, 2023",
    color: "green",
  },
  {
    txName: "VAT",
    whatUsed: "Debit",
    debit: "-£9,928.72",
    date: "Feb 10, 2023",
    color: "red",
  },
  {
    txName: "Inheritance funds",
    whatUsed: "Credit",
    credit: "+£225,000.00",
    date: "Feb 2, 2023",
    color: "green",
  },
];
